### ISSUE TITLE
Nmea string with correct number of parts is parsed incorrectly

### ISSUE THREAD

**Issue by tsandeepkumar** [EddieGarmon/GraduatedCylinder#1]
the string "$GPRMC,145710.00,A,3605.08678,N,07958.72572,W,0.037,,180716,,,D*6B" has 13 parts but the code says its not a valid string. The Nmea string decoder class is giving an exception "Need to support NMEA 2.3".  Can I go ahead and attempt to fix this issue and send you a pull request?

**Comment by EddieGarmon** [comment]
Sure have a go at it :smile:

**Comment by EddieGarmon** [comment]
Thanks
